#include "RotateCut.au3" 
#include "FrameSearch.au3"

Func FirsList($drawingNumb)	
	
	WinWait('ТММ-3.'&$drawingNumb&' СБ.tif')
	RotateCut($drawingNumb)
	;Длинный код ККС
	MouseMove(897, 829, 0)
	MouseDown("left")
	MouseMove(1283, 857)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 10}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	;№ чертежа
	MouseMove(1000, 865, 5)
	MouseDown("left")
	MouseMove(1200, 900)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 9}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{r 2}")
	Sleep(200)
	MouseMove(1017, 996, 1)
	MouseDown("left")
	MouseMove(1230, 1030)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{r 2}")
	Sleep(200)
	
	;дата в штампе
	MouseMove(570, 800, 1)
	MouseDown("left")
	MouseMove(940, 1076, 5)
	MouseUp("left")
	MouseMove(800, 900, 1)
	MouseClick("left")
	MouseWheel("down", 10)
	;FrameSearch(900, 950, 875)
	#comments-start
	MouseMove(929, 631, 1)
	MouseDown("left")
	MouseMove(1043, 746, 5)
	MouseUp("left")
	Send("^x")
	MouseMove(900, 670, 1)
	MouseClick("left")
	MouseMove(929, 670, 1)
	MouseDown("left")
	MouseMove(1043, 746, 5)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	MouseMove(929, 753, 1)
	MouseDown("left")
	MouseMove(1043, 872, 5)
	MouseUp("left")
	Send("^x")
	MouseMove(900, 790, 1)
	MouseClick("left")
	MouseMove(929, 790, 1)
	MouseDown("left")
	MouseMove(1043, 872, 5)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	MouseMove(929, 877, 1)
	MouseDown("left")
	MouseMove(1043, 975, 5)
	MouseUp("left")
	Send("^x")
	MouseMove(900, 900, 1)
	MouseClick("left")
	MouseMove(929, 900, 1)
	MouseDown("left")
	MouseMove(1043, 975, 5)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	;Инвентарный №
	Send("{r}")
	MouseMove(300, 150, 1)
	MouseDown("left")
	MouseMove(409, 176, 5)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 17}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	;Дата(подпись)
	MouseMove(490, 150, 1)
	MouseDown("left")
	MouseMove(573, 177, 5)
	MouseUp("left")
	Send("^x")	
	MouseMove(480, 155, 1)
	MouseClick("left")
	MouseMove(490, 155, 1)
	MouseDown("left")
	MouseMove(573, 177, 5)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{l}")
	#comments-end
EndFunc