#include <ButtonConstants.au3>
#include <EditConstants.au3>
#include <GUIConstantsEx.au3>
#include <StaticConstants.au3>
#include <WindowsConstants.au3>

#Region ### START Koda GUI section ### Form=C:\Users\aa_shchendrygin\Desktop\dwgTemplate\SciTE4AutoIt3_Portable\test\GODMODE.kxf
$GODMODE = GUICreate("GODMODE", 335, 174, -1, -1)
$Header = GUICtrlCreateLabel("Введите первый и последний чертежи", 18, 15, 300, 24)
GUICtrlSetFont(-1, 12, 400, 0, "MS Sans Serif")
$First = GUICtrlCreateLabel("Первый чертеж:", 5, 50, 130, 20)
$txt1 = GUICtrlCreateLabel("ТММ-3.", 125, 50, 50, 20)
$FirstDraw = GUICtrlCreateInput("", 167, 46, 120, 20)
$txt3 = GUICtrlCreateLabel("СБ", 293, 50, 25, 20)
$Last = GUICtrlCreateLabel("Последний чертеж:", 5, 90, 130, 20)
$txt2 = GUICtrlCreateLabel("ТММ-3.", 125, 90, 50, 20)
$LastDraw = GUICtrlCreateInput("", 167, 86, 120, 20)
$txt4 = GUICtrlCreateLabel("СБ", 293, 90, 25, 20)
$OK = GUICtrlCreateButton("OK", 52, 130, 100, 30)
$Cancel = GUICtrlCreateButton("Cancel", 180, 130, 100, 30)
GUISetState(@SW_SHOW)
#EndRegion ### END Koda GUI section ###

Global $FirstDrawing
Global $LastDrawing

Func Progress()
	#Region ### START Koda GUI section ### Form=C:\Users\aa_shchendrygin\Desktop\dwgTemplate\SciTE4AutoIt3_Portable\test\Progress.kxf
	$Progress = GUICreate("Progress", 301, 143, -1, -1)
	$Progress1 = GUICtrlCreateProgress(25, 80, 250, 20)
	$Label1 = GUICtrlCreateLabel("Label1", 25, 30, 250, 30)
	GUISetState(@SW_SHOW)
	#EndRegion ### END Koda GUI section ###

	While 1
		$nMsg = GUIGetMsg()
		Switch $nMsg
			Case $GUI_EVENT_CLOSE
				ExitLoop
		EndSwitch
	WEnd

EndFunc


Func Save()
	;Сохранение
	Send("^s")
	WinWaitActive("Сохранение...", "")
	Send("{ENTER}")
	Send("{LEFT 1}")
	Send("{ENTER}")
EndFunc

Func PageDown()
	;переход на след. страницу
	Send("{PGDN}")
EndFunc


Func NextDraw()
	;переход на след. чертёж
	Send("{SPACE}")
EndFunc
Func Rotate($drawingNumb)
	$coord1  = PixelSearch(620, 100, 640, 125, 0x000000, 100)
	$coord2  = PixelSearch(1295, 100, 1275, 125, 0x000000, 100)
	$coord3  = PixelSearch(620, 1045, 650, 1020, 0x000000, 100)
	$coord4  = PixelSearch(1295, 1045, 1275, 1020, 0x000000, 100)

	If Not @error Then
		$angle1 = $coord1[1] - $coord2[1]
		$angle2 = $coord1[0] - $coord3[0]

		If $angle1 > 0 Then
			$reqAngle = 0 - Tan(($coord2[1] - $coord1[1])/($coord1[0] - $coord2[0]))
			Send("^u")
			WinWaitActive('Rotate by angle', "")
			Send($reqAngle)
			Send("{ENTER}")
		ElseIf $angle1 < 0 Then
			$reqAngle = 0 + Tan(($coord2[1] - $coord1[1])/($coord1[0] - $coord2[0]))
			Send("^u")
			WinWaitActive('Rotate by angle', "")
			Send($reqAngle)
			Send("{ENTER}")
		EndIf
		
		WinWait('ТММ-3.'&$drawingNumb&' СБ.tif')
		$coord1  = PixelSearch(620, 100, 640, 125, 0x000000, 100)
		$coord2  = PixelSearch(1295, 100, 1275, 125, 0x000000, 100)
		$coord3  = PixelSearch(620, 1045, 650, 1020, 0x000000, 100)
		$coord4  = PixelSearch(1295, 1045, 1275, 1020, 0x000000, 100)
		MouseMove($coord1[0] - 1, $coord1[1] - 1, 0)
		MouseDown("left")
		MouseMove($coord4[0] + 1, $coord4[1] + 1, 0)
		MouseUp("left")
		Send("^y")
	Else
		MsgBox(0, "Ошибка!", "Неудалось определить координаты")
	EndIf
EndFunc

Func dateFrameSearch()
	$outsideXY = PixelSearch(900, 875, 950, 875, 0x000000)
	$insideX = PixelSearch($outsideXY[0], $outsideXY[1], $outsideXY[0] + 9, $outsideXY[1], 0xFFFFFF)
	$insideXY = PixelSearch($insideX[0], $insideX[1] - 30, $insideX[0], $insideX[1], 0x000000, 2)

	If Not @error Then
			
		MouseMove($insideXY[0] - 1, $insideXY[1] + 3, 10)
		MouseDown("left")
		MouseMove($insideXY[0] + 112, $insideXY[1] + 120, 10)
		MouseUp("left")
		Send("^x")

		MouseMove($insideXY[0] - 1, $insideXY[1] - 121, 10)
		MouseDown("left")
		MouseMove($insideXY[0] + 112, $insideXY[1] - 3, 10)
		MouseUp("left")
		Send("^x")
		
		MouseMove($insideXY[0] - 1, $insideXY[1] - 242, 10)
		MouseDown("left")
		MouseMove($insideXY[0] + 113, $insideXY[1] - 128, 10)
		MouseUp("left")
		Send("^x")
	Else
		MsgBox(0, "Ошибка!", "Неудалось определить координаты")
	EndIf
EndFunc
Func FirsList($drawingNumb)	
	
	WinWait('ТММ-3.'&$drawingNumb&' СБ.tif')
	Rotate($drawingNumb)
	;Длинный код ККС
	MouseMove(897, 829, 0)
	MouseDown("left")
	MouseMove(1283, 857)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 10}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;№ чертежа
	MouseMove(1000, 865, 5)
	MouseDown("left")
	MouseMove(1200, 900)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 9}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	
	Send("{r 2}")
	Sleep(200)
	MouseMove(1017, 996, 1)
	MouseDown("left")
	MouseMove(1230, 1030)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{r 2}")
	Sleep(200)
	
	;дата в штампе
	MouseMove(570, 800, 1)
	MouseDown("left")
	MouseMove(940, 1076, 5)
	MouseUp("left")
	MouseMove(800, 900, 1)
	MouseClick("left")
	MouseWheel("down", 10)
	;dateFrameSearch()
	#comments-start

	MouseMove(929, 631, 1)
	MouseDown("left")
	MouseMove(1043, 746, 5)
	MouseUp("left")
	
	Send("^x")
		
	MouseMove(900, 670, 1)
	MouseClick("left")
	
	MouseMove(929, 670, 1)
	MouseDown("left")
	MouseMove(1043, 746, 5)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(929, 753, 1)
	MouseDown("left")
	MouseMove(1043, 872, 5)
	MouseUp("left")
	Send("^x")
	MouseMove(900, 790, 1)
	MouseClick("left")
	MouseMove(929, 790, 1)
	MouseDown("left")
	MouseMove(1043, 872, 5)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	
	MouseMove(929, 877, 1)
	MouseDown("left")
	MouseMove(1043, 975, 5)
	MouseUp("left")
	Send("^x")
	MouseMove(900, 900, 1)
	MouseClick("left")
	MouseMove(929, 900, 1)
	MouseDown("left")
	MouseMove(1043, 975, 5)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Инвентарный №
	Send("{r}")

	MouseMove(300, 150, 1)
	MouseDown("left")
	MouseMove(409, 176, 5)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 17}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Дата(подпись)
	MouseMove(490, 150, 1)
	MouseDown("left")
	MouseMove(573, 177, 5)
	MouseUp("left")
	Send("^x")
	
	MouseMove(480, 155, 1)
	MouseClick("left")
	MouseMove(490, 155, 1)
	MouseDown("left")
	MouseMove(573, 177, 5)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{l}")
	#comments-end
EndFunc
Func RusTT($drawingNumb)

	WinWait('ТММ-3.'&$drawingNumb&' СБ.tif')
	Rotate($drawingNumb)
	;№ чертежа
	MouseMove(980, 850)
	MouseDown("left")
	MouseMove(1170, 885)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 9}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	Send("{r 2}")
	MouseMove(1020, 980)
	MouseDown("left")
	MouseMove(1210, 1013)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{r 2}")

	;ТТ
	MouseMove(700, 400)
	MouseDown("left")
	MouseMove(1270, 480)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 14}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;дата в штампе
	MouseMove(570, 800)
	MouseDown("left")
	MouseMove(950, 1080)
	MouseUp("left")
	MouseMove(800, 900)
	MouseClick("left")
	MouseMove(948, 561)
	MouseDown("left")
	MouseMove(1057, 615)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	MouseMove(948, 620)
	MouseDown("left")
	MouseMove(1057, 674)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	MouseMove(948, 736)
	MouseDown("left")
	MouseMove(1057, 793)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	MouseMove(948, 796)
	MouseDown("left")
	MouseMove(1057, 853)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	MouseMove(948, 856)
	MouseDown("left")
	MouseMove(1057, 911)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Инвентарный №
	Send("{r}")
	MouseMove(335, 170)
	MouseDown("left")
	MouseMove(437, 196)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 17}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Дата(подпись)
	MouseMove(510, 173)
	MouseDown("left")
	MouseMove(590, 197)
	MouseUp("left")
	Send("^x")
	MouseMove(520, 150)
	MouseClick("left")
	MouseMove(510, 177)
	MouseDown("left")
	MouseMove(590, 200)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{l}")
EndFunc

Func EngTT($drawingNumb)
		
	WinWait('ТММ-3.'&$drawingNumb&' СБ.tif')
	Rotate($drawingNumb)
	;Длинный код ККС
	MouseMove(901, 846)
	MouseDown("left")
	MouseMove(1271, 874)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 10}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;№ чертежа
	MouseMove(983, 890)
	MouseDown("left")
	MouseMove(1170, 925)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 9}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	Send("{r 2}")
	MouseMove(1014, 982)
	MouseDown("left")
	MouseMove(1200, 1015)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{r 2}")

	;ТТ
	MouseMove(700, 400)
	MouseDown("left")
	MouseMove(1270, 486)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 13}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;дата в штампе
	MouseMove(570, 670)
	MouseDown("left")
	MouseMove(920, 1060)
	MouseUp("left")
	MouseMove(700, 800)
	MouseClick("left")
	MouseMove(721, 768)
	MouseDown("left")
	MouseMove(795, 828)
	MouseUp("left")
	Send("^x")
	MouseMove(710, 768)
	MouseClick("left")
	MouseMove(721, 788)
	MouseDown("left")
	MouseMove(795, 828)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	MouseMove(721, 831)
	MouseDown("left")
	MouseMove(795, 894)
	MouseUp("left")
	Send("^x")
	MouseMove(710, 849)
	MouseClick("left")
	MouseMove(721, 849)
	MouseDown("left")
	MouseMove(795, 894)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	MouseMove(721, 896)
	MouseDown("left")
	MouseMove(795, 956)
	MouseUp("left")
	Send("^x")
	MouseMove(710, 916)
	MouseClick("left")
	MouseMove(721, 916)
	MouseDown("left")
	MouseMove(795, 956)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Инвентарный №
	Send("{r}")

	MouseMove(333, 171)
	MouseDown("left")
	MouseMove(438, 196)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 17}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Дата(подпись)
	MouseMove(515, 172)
	MouseDown("left")
	MouseMove(594, 198)
	MouseUp("left")
	Send("^x")
	MouseMove(610, 200)
	MouseClick("left")
	MouseMove(515, 175)
	MouseDown("left")
	MouseMove(594, 198)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{l}")

EndFunc

Func RusSpecif($drawingNumb)
		
	WinWait('ТММ-3.'&$drawingNumb&' СБ.tif')
	Rotate($drawingNumb)
	;KKS
	MouseMove(840, 860)
	MouseDown("left")
	MouseMove(1140, 880)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 18}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;№ чертежа
	MouseMove(1030, 910)
	MouseDown("left")
	MouseMove(1140, 930)
	MouseUp("left")
	Send("^x")
	MouseMove(1000, 915)
	MouseClick("left")
	MouseMove(1040, 910)
	MouseDown("left")
	MouseMove(1126, 926)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 3}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	MouseMove(765, 241)
	MouseDown("left")
	MouseMove(863, 258)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Дата в штампе
	MouseMove(560, 860)
	MouseDown("left")
	MouseMove(950, 1070)
	MouseUp("left")
	MouseMove(800, 950)
	MouseClick("left")
	MouseMove(1244, 507)
	MouseDown("left")
	MouseMove(1395, 581)
	MouseUp("left")
	
	Send("^x")
	MouseMove(1200, 500)
	MouseClick("left")
	MouseMove(1244, 520)
	MouseDown("left")
	MouseMove(1395, 581)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(1244, 585)
	MouseDown("left")
	MouseMove(1395, 660)
	MouseUp("left")
	Send("^x")
	MouseMove(1200, 565)
	MouseClick("left")
	MouseMove(1244, 600)
	MouseDown("left")
	MouseMove(1395, 660)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(1244, 665)
	MouseDown("left")
	MouseMove(1395, 740)
	MouseUp("left")
	Send("^x")
	MouseMove(1200, 665)
	MouseClick("left")
	MouseMove(1244, 680)
	MouseDown("left")
	MouseMove(1395, 740)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(1244, 745)
	MouseDown("left")
	MouseMove(1395, 820)
	MouseUp("left")
	Send("^x")
	MouseMove(1200, 745)
	MouseClick("left")
	MouseMove(1244, 760)
	MouseDown("left")
	MouseMove(1395, 820)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(1244, 825)
	MouseDown("left")
	MouseMove(1395, 893)
	MouseUp("left")
	Send("^x")
	MouseMove(1200, 825)
	MouseClick("left")
	MouseMove(1244, 835)
	MouseDown("left")
	MouseMove(1395, 893)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Инвентарный №
	Send("{r}")
	MouseMove(323, 168)
	MouseDown("left")
	MouseMove(478, 196)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 17}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Дата(подпись)
	MouseMove(530, 170)
	MouseDown("left")
	MouseMove(590, 196)
	MouseUp("left")
	Send("^x")
	MouseMove(530, 150)
	MouseClick("left")
	MouseMove(530, 175)
	MouseDown("left")
	MouseMove(590, 196)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{l}")
EndFunc

Func EngSpecif($drawingNumb)
		
	WinWait('ТММ-3.'&$drawingNumb&' СБ.tif')
	Rotate($drawingNumb)
	;Длинный код ККС
	MouseMove(900, 859)
	MouseDown("left")
	MouseMove(1271, 886)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 10}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;№ чертежа
	MouseMove(987, 895)
	MouseDown("left")
	MouseMove(1142, 927)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 9}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;№ чертежа таблица
	MouseMove(770, 254)
	MouseDown("left")
	MouseMove(880, 280)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 5}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;дата в штампе
	MouseMove(570, 870)
	MouseDown("left")
	MouseMove(920, 1060)
	MouseUp("left")
	MouseMove(780, 900)
	MouseClick("left")
	MouseMove(1309, 434)
	MouseDown("left")
	MouseMove(1461, 564)
	MouseUp("left")
	Send("^x")
	MouseMove(1280, 500)
	MouseClick("left")
	MouseMove(1309, 470)
	MouseDown("left")
	MouseMove(1461, 564)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(1309, 568)
	MouseDown("left")
	MouseMove(1461, 700)
	MouseUp("left")
	Send("^x")
	MouseMove(1280, 600)
	MouseClick("left")
	MouseMove(1309, 600)
	MouseDown("left")
	MouseMove(1461, 700)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(1309, 705)
	MouseDown("left")
	MouseMove(1461, 833)
	MouseUp("left")
	Send("^x")
	MouseMove(1280, 736)
	MouseClick("left")
	MouseMove(1309, 736)
	MouseDown("left")
	MouseMove(1461, 833)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Инвентарный №
	Send("{r}")

	MouseMove(339, 169)
	MouseDown("left")
	MouseMove(444, 196)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 17}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Дата(подпись)
	MouseMove(520, 169)
	MouseDown("left")
	MouseMove(600, 196)
	MouseUp("left")
	Send("^x")

	MouseMove(510, 175)
	MouseClick("left")

	MouseMove(520, 175)
	MouseDown("left")
	MouseMove(600, 196)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{l}")

EndFunc



Func Edit($FirstDrawing, $LastDrawing)
	$count = $LastDrawing - $FirstDrawing
	For $i = 0 to $count Step 1
		$CurrDraw = $FirstDrawing + $i
		
		;Progress()
		;GUICtrlSetData($Progress, $i)
		;WinActivate('ТММ-3.'&$CurrDraw&' СБ.tif ')
		FirsList($CurrDraw)
		;Save()
		;PageDown()
		;RusTT($CurrDraw)
		;Save()
		;PageDown()
		;EngTT($CurrDraw)
		;Save()
		;PageDown()
		;RusSpecif($CurrDraw)
		;PageDown()
		;Save()
		;EngSpecif($CurrDraw)
		;Save()
		;NextDraw()
	Next
	Exit
EndFunc


While 1
	$nMsg = GUIGetMsg()
	Switch $nMsg
		Case $OK
			$FirstDrawing = GUICtrlRead($FirstDraw)
			$LastDrawing = GUICtrlRead($LastDraw)
			GUISetState(@SW_HIDE)
			Edit($FirstDrawing, $LastDrawing)
		Case $Cancel
			Exit
		Case $GUI_EVENT_CLOSE
			Exit
	EndSwitch
WEnd