#include <RotateCut.au3> 
#include <FrameSearch.au3>

Func Specif_ENG($drawingNumb)
		
	WinWait('ТММ-3.'&$drawingNumb&' СБ.tif')
	RotateCut()
	;Длинный код ККС
	MouseMove(900, 859)
	MouseDown("left")
	MouseMove(1271, 886)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 10}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;№ чертежа
	MouseMove(987, 895)
	MouseDown("left")
	MouseMove(1142, 927)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 9}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;№ чертежа таблица
	MouseMove(770, 254)
	MouseDown("left")
	MouseMove(880, 280)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 5}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;дата в штампе
	MouseMove(570, 870)
	MouseDown("left")
	MouseMove(920, 1060)
	MouseUp("left")
	MouseMove(780, 900)
	MouseClick("left")
	MouseMove(1309, 434)
	MouseDown("left")
	MouseMove(1461, 564)
	MouseUp("left")
	Send("^x")
	MouseMove(1280, 500)
	MouseClick("left")
	MouseMove(1309, 470)
	MouseDown("left")
	MouseMove(1461, 564)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(1309, 568)
	MouseDown("left")
	MouseMove(1461, 700)
	MouseUp("left")
	Send("^x")
	MouseMove(1280, 600)
	MouseClick("left")
	MouseMove(1309, 600)
	MouseDown("left")
	MouseMove(1461, 700)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(1309, 705)
	MouseDown("left")
	MouseMove(1461, 833)
	MouseUp("left")
	Send("^x")
	MouseMove(1280, 736)
	MouseClick("left")
	MouseMove(1309, 736)
	MouseDown("left")
	MouseMove(1461, 833)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Инвентарный №
	Send("{r}")

	MouseMove(339, 169)
	MouseDown("left")
	MouseMove(444, 196)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 17}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Дата(подпись)
	MouseMove(520, 169)
	MouseDown("left")
	MouseMove(600, 196)
	MouseUp("left")
	Send("^x")

	MouseMove(510, 175)
	MouseClick("left")

	MouseMove(520, 175)
	MouseDown("left")
	MouseMove(600, 196)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{l}")

EndFunc