#include <RotateCut.au3> 
#include <FrameSearch.au3>

Func Specif_RUS($drawingNumb)
		
	WinWait('ТММ-3.'&$drawingNumb&' СБ.tif')
	RotateCut()
	;KKS
	MouseMove(840, 860)
	MouseDown("left")
	MouseMove(1140, 880)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 18}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;№ чертежа
	MouseMove(1030, 910)
	MouseDown("left")
	MouseMove(1140, 930)
	MouseUp("left")
	Send("^x")
	MouseMove(1000, 915)
	MouseClick("left")
	MouseMove(1040, 910)
	MouseDown("left")
	MouseMove(1126, 926)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 3}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	MouseMove(765, 241)
	MouseDown("left")
	MouseMove(863, 258)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Дата в штампе
	MouseMove(560, 860)
	MouseDown("left")
	MouseMove(950, 1070)
	MouseUp("left")
	MouseMove(800, 950)
	MouseClick("left")
	MouseMove(1244, 507)
	MouseDown("left")
	MouseMove(1395, 581)
	MouseUp("left")
	
	Send("^x")
	MouseMove(1200, 500)
	MouseClick("left")
	MouseMove(1244, 520)
	MouseDown("left")
	MouseMove(1395, 581)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(1244, 585)
	MouseDown("left")
	MouseMove(1395, 660)
	MouseUp("left")
	Send("^x")
	MouseMove(1200, 565)
	MouseClick("left")
	MouseMove(1244, 600)
	MouseDown("left")
	MouseMove(1395, 660)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(1244, 665)
	MouseDown("left")
	MouseMove(1395, 740)
	MouseUp("left")
	Send("^x")
	MouseMove(1200, 665)
	MouseClick("left")
	MouseMove(1244, 680)
	MouseDown("left")
	MouseMove(1395, 740)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(1244, 745)
	MouseDown("left")
	MouseMove(1395, 820)
	MouseUp("left")
	Send("^x")
	MouseMove(1200, 745)
	MouseClick("left")
	MouseMove(1244, 760)
	MouseDown("left")
	MouseMove(1395, 820)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	MouseMove(1244, 825)
	MouseDown("left")
	MouseMove(1395, 893)
	MouseUp("left")
	Send("^x")
	MouseMove(1200, 825)
	MouseClick("left")
	MouseMove(1244, 835)
	MouseDown("left")
	MouseMove(1395, 893)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Инвентарный №
	Send("{r}")
	MouseMove(323, 168)
	MouseDown("left")
	MouseMove(478, 196)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 17}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Дата(подпись)
	MouseMove(530, 170)
	MouseDown("left")
	MouseMove(590, 196)
	MouseUp("left")
	Send("^x")
	MouseMove(530, 150)
	MouseClick("left")
	MouseMove(530, 175)
	MouseDown("left")
	MouseMove(590, 196)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{l}")
EndFunc