#include <RotateCut.au3> 
#include <FrameSearch.au3>

Func TT_ENG($drawingNumb)
		
	WinWait('ТММ-3.'&$drawingNumb&' СБ.tif')
	RotateCut()
	;Длинный код ККС
	MouseMove(901, 846)
	MouseDown("left")
	MouseMove(1271, 874)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 10}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;№ чертежа
	MouseMove(983, 890)
	MouseDown("left")
	MouseMove(1170, 925)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 9}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	Send("{r 2}")
	MouseMove(1014, 982)
	MouseDown("left")
	MouseMove(1200, 1015)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{r 2}")

	;ТТ
	MouseMove(700, 400)
	MouseDown("left")
	MouseMove(1270, 486)
	MouseUp("left")
	Send("^x")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 13}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;дата в штампе
	MouseMove(570, 670)
	MouseDown("left")
	MouseMove(920, 1060)
	MouseUp("left")
	MouseMove(700, 800)
	MouseClick("left")
	MouseMove(721, 768)
	MouseDown("left")
	MouseMove(795, 828)
	MouseUp("left")
	Send("^x")
	MouseMove(710, 768)
	MouseClick("left")
	MouseMove(721, 788)
	MouseDown("left")
	MouseMove(795, 828)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	MouseMove(721, 831)
	MouseDown("left")
	MouseMove(795, 894)
	MouseUp("left")
	Send("^x")
	MouseMove(710, 849)
	MouseClick("left")
	MouseMove(721, 849)
	MouseDown("left")
	MouseMove(795, 894)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	MouseMove(721, 896)
	MouseDown("left")
	MouseMove(795, 956)
	MouseUp("left")
	Send("^x")
	MouseMove(710, 916)
	MouseClick("left")
	MouseMove(721, 916)
	MouseDown("left")
	MouseMove(795, 956)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Инвентарный №
	Send("{r}")

	MouseMove(333, 171)
	MouseDown("left")
	MouseMove(438, 196)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 17}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

	;Дата(подпись)
	MouseMove(515, 172)
	MouseDown("left")
	MouseMove(594, 198)
	MouseUp("left")
	Send("^x")
	MouseMove(610, 200)
	MouseClick("left")
	MouseMove(515, 175)
	MouseDown("left")
	MouseMove(594, 198)
	MouseUp("left")
	Send("^t")
	WinWaitActive("Нанесение текста на изображение", "")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
	Send("{DOWN 6}")
	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Send("{l}")

EndFunc