Func InvFrameSearch($CurrDraw, $date = "0", $InvNo = 0, $X1 = 280, $Y = 155, $X2 = 320)
	sleep(300)
	$outsideXY = PixelSearch($X1, $Y, $X2, $Y, 0x000000)
	$insideX = PixelSearch($outsideXY[0], $outsideXY[1], $outsideXY[0] + 9, $outsideXY[1], 0xFFFFFF, 50)
	$insideTopLeft = PixelSearch($insideX[0], $insideX[1] , $insideX[0], $insideX[1] - 30, 0x000000, 50)

	If Not @error Then

		MouseMove($insideTopLeft[0] + 1, $insideTopLeft[1] + 2, 5)
		MouseDown("left")
		MouseMove($insideTopLeft[0] + 110, $insideTopLeft[1] + 30, 5)
		MouseUp("left")
		Send("^x")
		Send("^t")
		WinWaitActive("Нанесение текста на изображение", "")
		ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
		Send("{DOWN 9}")
		MouseClick("left", 1000, 450, 10)
		Send("^a")
		Send($InvNo)
		ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
		MouseMove($insideTopLeft[0] + 190, $insideTopLeft[1] + 3, 5)
		MouseDown("left")
		MouseMove($insideTopLeft[0] + 272, $insideTopLeft[1] + 30, 5)
		MouseUp("left")
		Send("^x")
		MouseMove($insideTopLeft[0] + 272, $insideTopLeft[1] + 35, 5)
		MouseClick("left")
		MouseMove($insideTopLeft[0] + 190, $insideTopLeft[1] + 10, 5)
		MouseDown("left")
		MouseMove($insideTopLeft[0] + 272, $insideTopLeft[1] + 30, 5)
		MouseUp("left")
		Send("^t")
		WinWaitActive("Нанесение текста на изображение", "")
		ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
		Send("{DOWN 10}")
		MouseClick("left", 1000, 450, 10)
		Send("^a")
		Send($date)
		ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
	Else
		writeLog($CurrDraw, "инв. № и даты")
	EndIf
EndFunc

;InvFrameSearch()