;~ #include <RotateCut.au3>

Func TT_RUS($CurrDraw, $CurrInvNo, $CurrDate)

	WinWait('ТММ-3.'&$CurrDraw&' СБ.tif')
	RotateCut($CurrDraw)
	;№ чертежа
	DrawingNumFrameSearch($CurrDraw)
;~ 	Send("^t")
;~ 	WinWaitActive("Нанесение текста на изображение", "")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
;~ 	Send("{DOWN 9}")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

;~ 	Send("{r 2}")
;~ 	MouseMove(1020, 980)
;~ 	MouseDown("left")
;~ 	MouseMove(1210, 1013)
;~ 	MouseUp("left")
;~ 	Send("^t")
;~ 	WinWaitActive("Нанесение текста на изображение", "")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
;~ 	Send("{r 2}")

;~ 	;ТТ
;~ 	MouseMove(700, 400)
;~ 	MouseDown("left")
;~ 	MouseMove(1270, 480)
;~ 	MouseUp("left")
;~ 	Send("^x")
;~ 	Send("^t")
;~ 	WinWaitActive("Нанесение текста на изображение", "")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
;~ 	Send("{DOWN 14}")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

;~ 	;дата в штампе
;~ 	MouseMove(570, 800)
;~ 	MouseDown("left")
;~ 	MouseMove(950, 1080)
;~ 	MouseUp("left")
;~ 	MouseMove(800, 900)
;~ 	MouseClick("left")
;~ 	MouseMove(948, 561)
;~ 	MouseDown("left")
;~ 	MouseMove(1057, 615)
;~ 	MouseUp("left")
;~ 	Send("^x")
;~ 	Send("^t")
;~ 	WinWaitActive("Нанесение текста на изображение", "")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
;~ 	Send("{DOWN 6}")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
;~ 	MouseMove(948, 620)
;~ 	MouseDown("left")
;~ 	MouseMove(1057, 674)
;~ 	MouseUp("left")
;~ 	Send("^x")
;~ 	Send("^t")
;~ 	WinWaitActive("Нанесение текста на изображение", "")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
;~ 	MouseMove(948, 736)
;~ 	MouseDown("left")
;~ 	MouseMove(1057, 793)
;~ 	MouseUp("left")
;~ 	Send("^x")
;~ 	Send("^t")
;~ 	WinWaitActive("Нанесение текста на изображение", "")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
;~ 	MouseMove(948, 796)
;~ 	MouseDown("left")
;~ 	MouseMove(1057, 853)
;~ 	MouseUp("left")
;~ 	Send("^x")
;~ 	Send("^t")
;~ 	WinWaitActive("Нанесение текста на изображение", "")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
;~ 	MouseMove(948, 856)
;~ 	MouseDown("left")
;~ 	MouseMove(1057, 911)
;~ 	MouseUp("left")
;~ 	Send("^x")
;~ 	Send("^t")
;~ 	WinWaitActive("Нанесение текста на изображение", "")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

;~ 	;Инвентарный №
;~ 	Send("{r}")
;~ 	MouseMove(335, 170)
;~ 	MouseDown("left")
;~ 	MouseMove(437, 196)
;~ 	MouseUp("left")
;~ 	Send("^t")
;~ 	WinWaitActive("Нанесение текста на изображение", "")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
;~ 	Send("{DOWN 17}")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")

;~ 	;Дата(подпись)
;~ 	MouseMove(510, 173)
;~ 	MouseDown("left")
;~ 	MouseMove(590, 197)
;~ 	MouseUp("left")
;~ 	Send("^x")
;~ 	MouseMove(520, 150)
;~ 	MouseClick("left")
;~ 	MouseMove(510, 177)
;~ 	MouseDown("left")
;~ 	MouseMove(590, 200)
;~ 	MouseUp("left")
;~ 	Send("^t")
;~ 	WinWaitActive("Нанесение текста на изображение", "")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:ComboBox; TEXT:; INSTANCE:1]")
;~ 	Send("{DOWN 6}")
;~ 	ControlClick("Нанесение текста на изображение", "", "[CLASS:Button; TEXT:OK; INSTANCE:1]")
;~ 	Send("{l}")
EndFunc